#Every Message can use the minimessage api
#Don't use 'ยง' for color with minimessage
message:
  badFilename: "Please provide a correct file name!"
  alreadyUsedThread: "The music '%s' is already being played."
  listOfLoadedFile: "List of loaded music :"
  noFileLoaded: "No music are loaded at the moment."
  listCurrentlyPlayingMusic: "List of music that are currently being played :"
  noMusicCurrentlyBeingPlayed: "No music is currently being played"
  musicNameAlreadyInUse: "Name '%s' is already being used!"
  fileLoadedAs: "File '%s0' loaded as '%s1'"
  fileNotFound: "File '%s' not found"
  invalidFileFormat: "File format not supported !"
  invalidURL: "URL format is wrong."
  threadNotFound: "Invalid thread named '%s'"
  musicNotFound: "The music '%s' was not found! Maybe you can try to load it?"
  fileBeingPlayed: "<green>Playing music '%s0' as '%s1'</green>"
  invalidArgument: "Invalid argument, please provide a correct one"
  unloadedFile: "File '%s' unloaded"
  reloadConfig: "<red>Configuration reloaded"
  fileBeingBroadcast: "<green>Broadcasting music '%s0' as '%s1'</green>"
  
jukebox-distance: 16