#Every Message can use the minimessage api
#Don't use '§' for color with minimessage
message:
  badFilename: "Veuillez fournir un nom de fichier audio valide!"
  alreadyUsedThread: "L'identifiant '%s' est déjà utilisé par un autre processus"
  listOfLoadedFile: "Liste des fichiers chargés :"
  noFileLoaded: "Aucun fichier n'est actuellement chargé."
  listCurrentlyPlayingMusic: "Liste des musiques en cours de lecture :"
  noMusicCurrentlyBeingPlayed: "Aucune musique n'est actuellement en cours d'écoute"
  musicNameAlreadyInUse: "Le nom '%s' est déjà utilisé!"
  fileLoadedAs: "Fichier '%s0' chargé en tant que '%s1'"
  fileNotFound: "Fichier '%s' introuvable"
  invalidFileFormat: "Format de fichier invalide !"
  invalidURL: "URL Invalide."
  threadNotFound: "Processus '%s' introuvable."
  musicNotFound: "La musique '%s' est introuvable!"
  fileBeingPlayed: "<green>Lecture en cours du fichier '%s0' en tant que '%s1'</green>"
  invalidArgument: "Argument invalide, veuillez rentrer un argument valide"
  unloadedFile: "Fichier '%s' déchargé"
  reloadConfig: "<red>Config reload"
