name: MusicPlayer
version: 1.0.6
main: org.tetram26.plugin.MusicPlayerPlugin
description: A plugin that allow you to play PCM file into plasmo voice !
author: tetram26 A.K.A gaspardAlizand
api-version: '1.21.1'
depend:
  - PlasmoVoice
commands:
  music:
    permission: musicplayer.musicplayer